module "label" {
  source  = "cloudposse/label/null"
  version = "0.25.0"

  namespace   = var.namespace
  environment = var.environment
  name        = var.name
}

module "fluentbit_config" {
  source = "../../"

  name        = module.label.name
  log_sources = [{ name = "dotnet", container = var.dotnet_container }]
  context     = module.label.context
}

output "dotnet_parsers" {
  value       = module.fluentbit_config.log_config_parsers
  description = "The .NET parser configuration generated by the module."
}

output "dotnet_filters" {
  value       = module.fluentbit_config.log_config_filters
  description = "The .NET filter configuration generated by the module."
}
